spring:
  application:
    name: gateway

server:
  port: 8080


zuul:
  routes:
    weather:
      path: /weather/**
      url: http://localhost:9001/weather
    members:
      path: /members/**
      url: http://localhost:9001/members
    resources:
      path: /**
      url: http://localhost:9000/


